name = "steam-friend-finder-proxy"
main = "worker.js"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "steam_strangers"
database_name = "steam-strangers"
database_id = "001bb287-f734-4945-9fd7-f0c879edb5ff"
